# Auto-generated - include all compiled modules
include(${CMAKE_CURRENT_LIST_DIR}/usermod_algorithms/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_bitwise/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_counter/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_dict_operations/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_factorial/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_inventory/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_list_operations/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_math_utils/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_point/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_print_test/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/usermod_sensor/micropython.cmake)
