"""LVGL v9 bindings for MicroPython.

Generated from deps/lvgl/ headers (v9.5.0).
"""

__c_header__ = "lvgl.h"
__c_include_dirs__ = ["deps/lvgl/src"]

from typing import Callable, Generic, TypeVar

T = TypeVar("T")

class c_ptr(Generic[T]):
    pass

class c_int:
    pass

class c_uint:
    pass

class c_bool:
    pass

class c_str:
    pass

def c_struct(c_name: str, opaque: bool = True):
    def decorator(cls: type) -> type:
        return cls
    return decorator

def c_enum(c_name: str):
    def decorator(cls: type) -> type:
        return cls
    return decorator

@c_struct("lv_obj_t")
class LvObj:
    pass

@c_struct("lv_display_t")
class LvDisplay:
    pass

@c_struct("lv_event_t")
class LvEvent:
    pass

@c_struct("lv_style_t")
class LvStyle:
    pass

@c_struct("lv_event_dsc_t")
class LvEventDsc:
    pass

@c_enum("lv_event_code_t")
class LvEventCode:
    ALL: int = 0
    PRESSED: int = 1
    PRESSING: int = 2
    PRESS_LOST: int = 3
    SHORT_CLICKED: int = 4
    SINGLE_CLICKED: int = 5
    DOUBLE_CLICKED: int = 6
    TRIPLE_CLICKED: int = 7
    LONG_PRESSED: int = 8
    LONG_PRESSED_REPEAT: int = 9
    CLICKED: int = 10
    RELEASED: int = 11
    SCROLL_BEGIN: int = 12
    SCROLL_THROW_BEGIN: int = 13
    SCROLL_END: int = 14
    SCROLL: int = 15
    GESTURE: int = 16
    KEY: int = 17
    ROTARY: int = 18
    FOCUSED: int = 19
    DEFOCUSED: int = 20
    LEAVE: int = 21
    HIT_TEST: int = 22
    INDEV_RESET: int = 23
    HOVER_OVER: int = 24
    HOVER_LEAVE: int = 25
    COVER_CHECK: int = 26
    REFR_EXT_DRAW_SIZE: int = 27
    DRAW_MAIN_BEGIN: int = 28
    DRAW_MAIN: int = 29
    DRAW_MAIN_END: int = 30
    DRAW_POST_BEGIN: int = 31
    DRAW_POST: int = 32
    DRAW_POST_END: int = 33
    DRAW_TASK_ADDED: int = 34
    VALUE_CHANGED: int = 35
    INSERT: int = 36
    REFRESH: int = 37
    READY: int = 38
    CANCEL: int = 39
    STATE_CHANGED: int = 40
    CREATE: int = 41
    DELETE: int = 42
    CHILD_CHANGED: int = 43
    CHILD_CREATED: int = 44
    CHILD_DELETED: int = 45
    SCREEN_UNLOAD_START: int = 46
    SCREEN_LOAD_START: int = 47
    SCREEN_LOADED: int = 48
    SCREEN_UNLOADED: int = 49
    SIZE_CHANGED: int = 50
    STYLE_CHANGED: int = 51
    LAYOUT_CHANGED: int = 52
    GET_SELF_SIZE: int = 53

@c_enum("lv_obj_flag_t")
class LvObjFlag:
    HIDDEN: int = 1 << 0
    CLICKABLE: int = 1 << 1
    CLICK_FOCUSABLE: int = 1 << 2
    CHECKABLE: int = 1 << 3
    SCROLLABLE: int = 1 << 4
    SCROLL_ELASTIC: int = 1 << 5
    SCROLL_MOMENTUM: int = 1 << 6
    SCROLL_ONE: int = 1 << 7
    SNAPPABLE: int = 1 << 14
    PRESS_LOCK: int = 1 << 15
    EVENT_BUBBLE: int = 1 << 16
    GESTURE_BUBBLE: int = 1 << 17
    ADV_HITTEST: int = 1 << 18
    IGNORE_LAYOUT: int = 1 << 19
    FLOATING: int = 1 << 20
    SEND_DRAW_TASK_EVENTS: int = 1 << 21
    OVERFLOW_VISIBLE: int = 1 << 22
    FLEX_IN_NEW_TRACK: int = 1 << 23

@c_enum("lv_align_t")
class LvAlign:
    DEFAULT: int = 0
    TOP_LEFT: int = 1
    TOP_MID: int = 2
    TOP_RIGHT: int = 3
    BOTTOM_LEFT: int = 4
    BOTTOM_MID: int = 5
    BOTTOM_RIGHT: int = 6
    LEFT_MID: int = 7
    RIGHT_MID: int = 8
    CENTER: int = 9

EventCallback = Callable[[c_ptr[LvEvent]], None]

# -- Screen --

def lv_screen_active() -> c_ptr[LvObj]: ...
def lv_screen_load(scr: c_ptr[LvObj]) -> None: ...
def lv_screen_load_anim(scr: c_ptr[LvObj], anim_type: c_int, time: c_uint, delay: c_uint, auto_del: c_bool) -> None: ...
def lv_layer_top() -> c_ptr[LvObj]: ...
def lv_layer_sys() -> c_ptr[LvObj]: ...

# -- Object core --

def lv_obj_create(parent: c_ptr[LvObj] | None) -> c_ptr[LvObj]: ...
def lv_obj_delete(obj: c_ptr[LvObj]) -> None: ...
def lv_obj_clean(obj: c_ptr[LvObj]) -> None: ...
def lv_obj_add_flag(obj: c_ptr[LvObj], flag: c_uint) -> None: ...
def lv_obj_remove_flag(obj: c_ptr[LvObj], flag: c_uint) -> None: ...
def lv_obj_add_state(obj: c_ptr[LvObj], state: c_uint) -> None: ...
def lv_obj_remove_state(obj: c_ptr[LvObj], state: c_uint) -> None: ...
def lv_obj_has_flag(obj: c_ptr[LvObj], flag: c_uint) -> c_bool: ...
def lv_obj_has_state(obj: c_ptr[LvObj], state: c_uint) -> c_bool: ...
def lv_obj_set_user_data(obj: c_ptr[LvObj], user_data: c_ptr[object] | None) -> None: ...
def lv_obj_is_valid(obj: c_ptr[LvObj]) -> c_bool: ...

# -- Object position and size --

def lv_obj_set_pos(obj: c_ptr[LvObj], x: c_int, y: c_int) -> None: ...
def lv_obj_set_x(obj: c_ptr[LvObj], x: c_int) -> None: ...
def lv_obj_set_y(obj: c_ptr[LvObj], y: c_int) -> None: ...
def lv_obj_set_size(obj: c_ptr[LvObj], w: c_int, h: c_int) -> None: ...
def lv_obj_set_width(obj: c_ptr[LvObj], w: c_int) -> None: ...
def lv_obj_set_height(obj: c_ptr[LvObj], h: c_int) -> None: ...
def lv_obj_set_content_width(obj: c_ptr[LvObj], w: c_int) -> None: ...
def lv_obj_set_content_height(obj: c_ptr[LvObj], h: c_int) -> None: ...
def lv_obj_set_layout(obj: c_ptr[LvObj], layout: c_uint) -> None: ...
def lv_obj_center(obj: c_ptr[LvObj]) -> None: ...
def lv_obj_align(obj: c_ptr[LvObj], align: c_int, x_ofs: c_int, y_ofs: c_int) -> None: ...
def lv_obj_set_ext_click_area(obj: c_ptr[LvObj], size: c_int) -> None: ...
def lv_obj_get_x(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_y(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_width(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_height(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_content_width(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_content_height(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_self_width(obj: c_ptr[LvObj]) -> c_int: ...
def lv_obj_get_self_height(obj: c_ptr[LvObj]) -> c_int: ...

# -- Object tree --

def lv_obj_get_screen(obj: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_obj_get_parent(obj: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_obj_get_child(obj: c_ptr[LvObj], idx: c_int) -> c_ptr[LvObj]: ...
def lv_obj_get_child_count(obj: c_ptr[LvObj]) -> c_uint: ...
def lv_obj_get_index(obj: c_ptr[LvObj]) -> c_uint: ...

# -- Events --

def lv_obj_add_event_cb(
    obj: c_ptr[LvObj],
    event_cb: EventCallback,
    filter: c_int,
    user_data: c_ptr[object] | None = None,
) -> None: ...
def lv_event_get_code(e: c_ptr[LvEvent]) -> c_int: ...
def lv_event_get_target_obj(e: c_ptr[LvEvent]) -> c_ptr[LvObj]: ...
def lv_event_get_current_target_obj(e: c_ptr[LvEvent]) -> c_ptr[LvObj]: ...

# -- Button widget (lv_button in v9) --

def lv_button_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...

# -- Label widget --

def lv_label_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_label_set_text(obj: c_ptr[LvObj], text: str) -> None: ...
def lv_label_set_text_static(obj: c_ptr[LvObj], text: str) -> None: ...
def lv_label_set_long_mode(obj: c_ptr[LvObj], long_mode: c_int) -> None: ...
def lv_label_set_recolor(obj: c_ptr[LvObj], en: c_bool) -> None: ...

# -- Slider widget --

def lv_slider_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_slider_set_value(obj: c_ptr[LvObj], value: c_int, anim: c_int) -> None: ...
def lv_slider_set_range(obj: c_ptr[LvObj], min_val: c_int, max_val: c_int) -> None: ...
def lv_slider_set_min_value(obj: c_ptr[LvObj], min_val: c_int) -> None: ...
def lv_slider_set_max_value(obj: c_ptr[LvObj], max_val: c_int) -> None: ...
def lv_slider_get_value(obj: c_ptr[LvObj]) -> c_int: ...
def lv_slider_get_min_value(obj: c_ptr[LvObj]) -> c_int: ...
def lv_slider_get_max_value(obj: c_ptr[LvObj]) -> c_int: ...

# -- Switch widget --

def lv_switch_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...

# -- Checkbox widget --

def lv_checkbox_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_checkbox_set_text(obj: c_ptr[LvObj], txt: str) -> None: ...
def lv_checkbox_set_text_static(obj: c_ptr[LvObj], txt: str) -> None: ...

# -- Bar widget --

def lv_bar_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_bar_set_value(obj: c_ptr[LvObj], value: c_int, anim: c_int) -> None: ...
def lv_bar_set_range(obj: c_ptr[LvObj], min_val: c_int, max_val: c_int) -> None: ...
def lv_bar_get_value(obj: c_ptr[LvObj]) -> c_int: ...
def lv_bar_get_min_value(obj: c_ptr[LvObj]) -> c_int: ...
def lv_bar_get_max_value(obj: c_ptr[LvObj]) -> c_int: ...

# -- Arc widget --

def lv_arc_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_arc_set_value(obj: c_ptr[LvObj], value: c_int) -> None: ...
def lv_arc_set_range(obj: c_ptr[LvObj], min_val: c_int, max_val: c_int) -> None: ...
def lv_arc_set_rotation(obj: c_ptr[LvObj], rotation: c_int) -> None: ...
def lv_arc_get_value(obj: c_ptr[LvObj]) -> c_int: ...
def lv_arc_get_min_value(obj: c_ptr[LvObj]) -> c_int: ...
def lv_arc_get_max_value(obj: c_ptr[LvObj]) -> c_int: ...

# =============================================================================
# COLOR API
# =============================================================================

@c_struct("lv_color_t", opaque=False)
class LvColor:
    pass

def lv_color_hex(hex_val: c_uint) -> LvColor: ...
def lv_color_make(r: c_uint, g: c_uint, b: c_uint) -> LvColor: ...
def lv_color_white() -> LvColor: ...
def lv_color_black() -> LvColor: ...
def lv_color_lighten(c: LvColor, lvl: c_uint) -> LvColor: ...
def lv_color_darken(c: LvColor, lvl: c_uint) -> LvColor: ...
def lv_color_mix(c1: LvColor, c2: LvColor, mix: c_uint) -> LvColor: ...

@c_enum("lv_palette_t")
class LvPalette:
    RED: int = 0
    PINK: int = 1
    PURPLE: int = 2
    DEEP_PURPLE: int = 3
    INDIGO: int = 4
    BLUE: int = 5
    LIGHT_BLUE: int = 6
    CYAN: int = 7
    TEAL: int = 8
    GREEN: int = 9
    LIGHT_GREEN: int = 10
    LIME: int = 11
    YELLOW: int = 12
    AMBER: int = 13
    ORANGE: int = 14
    DEEP_ORANGE: int = 15
    BROWN: int = 16
    BLUE_GREY: int = 17
    GREY: int = 18
    NONE: int = 19

def lv_palette_main(p: c_int) -> LvColor: ...
def lv_palette_lighten(p: c_int, lvl: c_int) -> LvColor: ...
def lv_palette_darken(p: c_int, lvl: c_int) -> LvColor: ...

# =============================================================================
# MORE ENUMS (State, Part, Direction, etc.)
# =============================================================================

@c_enum("lv_state_t")
class LvState:
    DEFAULT: int = 0x0000
    CHECKED: int = 0x0001
    FOCUSED: int = 0x0002
    FOCUS_KEY: int = 0x0004
    EDITED: int = 0x0008
    HOVERED: int = 0x0010
    PRESSED: int = 0x0020
    SCROLLED: int = 0x0040
    DISABLED: int = 0x0080
    USER_1: int = 0x1000
    USER_2: int = 0x2000
    USER_3: int = 0x4000
    USER_4: int = 0x8000
    ANY: int = 0xFFFF

@c_enum("lv_part_t")
class LvPart:
    MAIN: int = 0x000000
    SCROLLBAR: int = 0x010000
    INDICATOR: int = 0x020000
    KNOB: int = 0x030000
    SELECTED: int = 0x040000
    ITEMS: int = 0x050000
    CURSOR: int = 0x060000
    CUSTOM_FIRST: int = 0x080000
    ANY: int = 0x0F0000

@c_enum("lv_dir_t")
class LvDir:
    NONE: int = 0x00
    LEFT: int = 0x01
    RIGHT: int = 0x02
    TOP: int = 0x04
    BOTTOM: int = 0x08
    HOR: int = 0x03
    VER: int = 0x0C
    ALL: int = 0x0F

@c_enum("lv_border_side_t")
class LvBorderSide:
    NONE: int = 0x00
    BOTTOM: int = 0x01
    TOP: int = 0x02
    LEFT: int = 0x04
    RIGHT: int = 0x08
    FULL: int = 0x0F
    INTERNAL: int = 0x10

@c_enum("lv_text_align_t")
class LvTextAlign:
    AUTO: int = 0
    LEFT: int = 1
    CENTER: int = 2
    RIGHT: int = 3

@c_enum("lv_scrollbar_mode_t")
class LvScrollbarMode:
    OFF: int = 0
    ON: int = 1
    ACTIVE: int = 2
    AUTO: int = 3

@c_enum("lv_scroll_snap_t")
class LvScrollSnap:
    NONE: int = 0
    START: int = 1
    END: int = 2
    CENTER: int = 3

@c_enum("lv_base_dir_t")
class LvBaseDir:
    LTR: int = 0
    RTL: int = 1
    AUTO: int = 2

@c_enum("lv_blend_mode_t")
class LvBlendMode:
    NORMAL: int = 0
    ADDITIVE: int = 1
    SUBTRACTIVE: int = 2
    MULTIPLY: int = 3

@c_enum("lv_grad_dir_t")
class LvGradDir:
    NONE: int = 0
    VER: int = 1
    HOR: int = 2

@c_enum("lv_text_decor_t")
class LvTextDecor:
    NONE: int = 0x00
    UNDERLINE: int = 0x01
    STRIKETHROUGH: int = 0x02

@c_enum("lv_opa_t")
class LvOpa:
    TRANSP: int = 0
    COVER: int = 255

LV_OPA_TRANSP: int = 0
LV_OPA_0: int = 0
LV_OPA_10: int = 25
LV_OPA_20: int = 51
LV_OPA_30: int = 76
LV_OPA_40: int = 102
LV_OPA_50: int = 127
LV_OPA_60: int = 153
LV_OPA_70: int = 178
LV_OPA_80: int = 204
LV_OPA_90: int = 229
LV_OPA_100: int = 255
LV_OPA_COVER: int = 255

@c_enum("lv_label_long_mode_t")
class LvLabelLongMode:
    WRAP: int = 0
    DOT: int = 1
    SCROLL: int = 2
    SCROLL_CIRCULAR: int = 3
    CLIP: int = 4

@c_enum("lv_anim_enable_t")
class LvAnimEnable:
    OFF: int = 0
    ON: int = 1

LV_ANIM_OFF: int = 0
LV_ANIM_ON: int = 1

@c_enum("lv_scr_load_anim_t")
class LvScrLoadAnim:
    NONE: int = 0
    OVER_LEFT: int = 1
    OVER_RIGHT: int = 2
    OVER_TOP: int = 3
    OVER_BOTTOM: int = 4
    MOVE_LEFT: int = 5
    MOVE_RIGHT: int = 6
    MOVE_TOP: int = 7
    MOVE_BOTTOM: int = 8
    FADE_IN: int = 9
    FADE_OUT: int = 10
    OUT_LEFT: int = 11
    OUT_RIGHT: int = 12
    OUT_TOP: int = 13
    OUT_BOTTOM: int = 14

# =============================================================================
# STYLE API
# =============================================================================

def lv_style_init(style: c_ptr[LvStyle]) -> None: ...
def lv_style_reset(style: c_ptr[LvStyle]) -> None: ...

# -- Background --
def lv_style_set_bg_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_bg_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_bg_grad_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_bg_grad_dir(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_bg_main_stop(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_bg_grad_stop(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Border --
def lv_style_set_border_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_border_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_border_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_border_side(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_border_post(style: c_ptr[LvStyle], value: c_bool) -> None: ...

# -- Outline --
def lv_style_set_outline_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_outline_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_outline_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_outline_pad(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Shadow --
def lv_style_set_shadow_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_shadow_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_shadow_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_shadow_offset_x(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_shadow_offset_y(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_shadow_spread(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Padding --
def lv_style_set_pad_top(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_bottom(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_left(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_right(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_row(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_column(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_all(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_hor(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_ver(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_pad_gap(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Margin --
def lv_style_set_margin_top(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_margin_bottom(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_margin_left(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_margin_right(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Size --
def lv_style_set_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_min_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_max_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_height(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_min_height(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_max_height(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Position --
def lv_style_set_x(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_y(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_align(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_height(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_translate_x(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_translate_y(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_scale_x(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_scale_y(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_rotation(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_pivot_x(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_pivot_y(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_skew_x(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_transform_skew_y(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Text --
def lv_style_set_text_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_text_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_text_letter_space(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_text_line_space(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_text_decor(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_text_align(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Image --
def lv_style_set_image_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_image_recolor(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_image_recolor_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Line --
def lv_style_set_line_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_line_dash_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_line_dash_gap(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_line_rounded(style: c_ptr[LvStyle], value: c_bool) -> None: ...
def lv_style_set_line_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_line_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Arc --
def lv_style_set_arc_width(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_arc_rounded(style: c_ptr[LvStyle], value: c_bool) -> None: ...
def lv_style_set_arc_color(style: c_ptr[LvStyle], value: LvColor) -> None: ...
def lv_style_set_arc_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Misc --
def lv_style_set_radius(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_clip_corner(style: c_ptr[LvStyle], value: c_bool) -> None: ...
def lv_style_set_opa(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_blend_mode(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_layout(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_base_dir(style: c_ptr[LvStyle], value: c_int) -> None: ...

# -- Object style setters (inline style) --
def lv_obj_set_style_bg_color(obj: c_ptr[LvObj], value: LvColor, selector: c_uint) -> None: ...
def lv_obj_set_style_bg_opa(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_border_color(obj: c_ptr[LvObj], value: LvColor, selector: c_uint) -> None: ...
def lv_obj_set_style_border_width(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_border_opa(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_text_color(obj: c_ptr[LvObj], value: LvColor, selector: c_uint) -> None: ...
def lv_obj_set_style_text_opa(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_text_align(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_all(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_top(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_bottom(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_left(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_right(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_row(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_pad_column(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_radius(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_opa(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_width(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_height(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_shadow_color(obj: c_ptr[LvObj], value: LvColor, selector: c_uint) -> None: ...
def lv_obj_set_style_shadow_width(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...
def lv_obj_set_style_shadow_opa(obj: c_ptr[LvObj], value: c_int, selector: c_uint) -> None: ...

# -- Apply style to object --
def lv_obj_add_style(obj: c_ptr[LvObj], style: c_ptr[LvStyle], selector: c_uint) -> None: ...
def lv_obj_remove_style(obj: c_ptr[LvObj], style: c_ptr[LvStyle] | None, selector: c_uint) -> None: ...
def lv_obj_remove_style_all(obj: c_ptr[LvObj]) -> None: ...
def lv_obj_refresh_style(obj: c_ptr[LvObj], part: c_uint, prop: c_uint) -> None: ...

# =============================================================================
# FLEX LAYOUT API
# =============================================================================

@c_enum("lv_flex_flow_t")
class LvFlexFlow:
    ROW: int = 0x00
    COLUMN: int = 0x01
    ROW_WRAP: int = 0x02
    ROW_REVERSE: int = 0x04
    ROW_WRAP_REVERSE: int = 0x06
    COLUMN_WRAP: int = 0x03
    COLUMN_REVERSE: int = 0x05
    COLUMN_WRAP_REVERSE: int = 0x07

@c_enum("lv_flex_align_t")
class LvFlexAlign:
    START: int = 0
    END: int = 1
    CENTER: int = 2
    SPACE_EVENLY: int = 3
    SPACE_AROUND: int = 4
    SPACE_BETWEEN: int = 5

LV_FLEX_GROW: int = 1

def lv_obj_set_flex_flow(obj: c_ptr[LvObj], flow: c_uint) -> None: ...
def lv_obj_set_flex_grow(obj: c_ptr[LvObj], grow: c_uint) -> None: ...
def lv_obj_set_flex_align(obj: c_ptr[LvObj], main_place: c_uint, cross_place: c_uint, track_cross_place: c_uint) -> None: ...
def lv_style_set_flex_flow(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_flex_main_place(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_flex_cross_place(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_flex_track_place(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_flex_grow(style: c_ptr[LvStyle], value: c_uint) -> None: ...

# =============================================================================
# GRID LAYOUT API
# =============================================================================

@c_enum("lv_grid_align_t")
class LvGridAlign:
    START: int = 0
    CENTER: int = 1
    END: int = 2
    STRETCH: int = 3
    SPACE_EVENLY: int = 4
    SPACE_AROUND: int = 5
    SPACE_BETWEEN: int = 6

LV_GRID_CONTENT: int = 0x400001
LV_GRID_TEMPLATE_LAST: int = 0x400000

def lv_obj_set_grid_dsc_array(obj: c_ptr[LvObj], col_dsc: c_ptr[c_int], row_dsc: c_ptr[c_int]) -> None: ...
def lv_obj_set_grid_align(obj: c_ptr[LvObj], column_align: c_uint, row_align: c_uint) -> None: ...
def lv_obj_set_grid_cell(obj: c_ptr[LvObj], x_align: c_uint, col_pos: c_int, col_span: c_int, y_align: c_uint, row_pos: c_int, row_span: c_int) -> None: ...
def lv_style_set_grid_column_dsc_array(style: c_ptr[LvStyle], value: c_ptr[c_int]) -> None: ...
def lv_style_set_grid_row_dsc_array(style: c_ptr[LvStyle], value: c_ptr[c_int]) -> None: ...
def lv_style_set_grid_column_align(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_grid_row_align(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_grid_cell_column_pos(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_grid_cell_column_span(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_grid_cell_row_pos(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_grid_cell_row_span(style: c_ptr[LvStyle], value: c_int) -> None: ...
def lv_style_set_grid_cell_x_align(style: c_ptr[LvStyle], value: c_uint) -> None: ...
def lv_style_set_grid_cell_y_align(style: c_ptr[LvStyle], value: c_uint) -> None: ...

# =============================================================================
# ANIMATION API
# =============================================================================

@c_struct("lv_anim_t")
class LvAnim:
    pass

AnimExecCallback = Callable[[c_ptr[object], c_int], None]
AnimPathCallback = Callable[[c_ptr[LvAnim]], c_int]
AnimReadyCallback = Callable[[c_ptr[LvAnim]], None]
AnimStartCallback = Callable[[c_ptr[LvAnim]], None]
AnimDeletedCallback = Callable[[c_ptr[LvAnim]], None]

def lv_anim_init(a: c_ptr[LvAnim]) -> None: ...
def lv_anim_set_var(a: c_ptr[LvAnim], var: c_ptr[object]) -> None: ...
def lv_anim_set_exec_cb(a: c_ptr[LvAnim], exec_cb: AnimExecCallback) -> None: ...
def lv_anim_set_duration(a: c_ptr[LvAnim], duration: c_uint) -> None: ...
def lv_anim_set_time(a: c_ptr[LvAnim], time: c_uint) -> None: ...
def lv_anim_set_delay(a: c_ptr[LvAnim], delay: c_uint) -> None: ...
def lv_anim_set_values(a: c_ptr[LvAnim], start: c_int, end: c_int) -> None: ...
def lv_anim_set_path_cb(a: c_ptr[LvAnim], path_cb: AnimPathCallback) -> None: ...
def lv_anim_set_start_cb(a: c_ptr[LvAnim], start_cb: AnimStartCallback | None) -> None: ...
def lv_anim_set_ready_cb(a: c_ptr[LvAnim], ready_cb: AnimReadyCallback | None) -> None: ...
def lv_anim_set_deleted_cb(a: c_ptr[LvAnim], deleted_cb: AnimDeletedCallback | None) -> None: ...
def lv_anim_set_playback_time(a: c_ptr[LvAnim], time: c_uint) -> None: ...
def lv_anim_set_playback_delay(a: c_ptr[LvAnim], delay: c_uint) -> None: ...
def lv_anim_set_repeat_count(a: c_ptr[LvAnim], cnt: c_uint) -> None: ...
def lv_anim_set_repeat_delay(a: c_ptr[LvAnim], delay: c_uint) -> None: ...
def lv_anim_set_early_apply(a: c_ptr[LvAnim], en: c_bool) -> None: ...
def lv_anim_start(a: c_ptr[LvAnim]) -> c_ptr[LvAnim]: ...
def lv_anim_delete(var: c_ptr[object], exec_cb: AnimExecCallback | None) -> c_bool: ...
def lv_anim_delete_all() -> None: ...
def lv_anim_get_delay(a: c_ptr[LvAnim]) -> c_uint: ...
def lv_anim_get_time(a: c_ptr[LvAnim]) -> c_uint: ...
def lv_anim_get_repeat_count(a: c_ptr[LvAnim]) -> c_uint: ...

# -- Built-in path callbacks --
def lv_anim_path_linear(a: c_ptr[LvAnim]) -> c_int: ...
def lv_anim_path_ease_in(a: c_ptr[LvAnim]) -> c_int: ...
def lv_anim_path_ease_out(a: c_ptr[LvAnim]) -> c_int: ...
def lv_anim_path_ease_in_out(a: c_ptr[LvAnim]) -> c_int: ...
def lv_anim_path_overshoot(a: c_ptr[LvAnim]) -> c_int: ...
def lv_anim_path_bounce(a: c_ptr[LvAnim]) -> c_int: ...
def lv_anim_path_step(a: c_ptr[LvAnim]) -> c_int: ...

LV_ANIM_REPEAT_INFINITE: int = 0xFFFF
LV_ANIM_PLAYTIME_INFINITE: int = 0xFFFFFFFF

# =============================================================================
# MORE WIDGETS
# =============================================================================

# -- Dropdown widget --

def lv_dropdown_create(parent: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_dropdown_set_text(obj: c_ptr[LvObj], txt: str | None) -> None: ...
def lv_dropdown_set_options(obj: c_ptr[LvObj], options: str) -> None: ...
def lv_dropdown_set_options_static(obj: c_ptr[LvObj], options: str) -> None: ...
def lv_dropdown_add_option(obj: c_ptr[LvObj], option: str, pos: c_uint) -> None: ...
def lv_dropdown_clear_options(obj: c_ptr[LvObj]) -> None: ...
def lv_dropdown_set_selected(obj: c_ptr[LvObj], sel_opt: c_uint) -> None: ...
def lv_dropdown_set_dir(obj: c_ptr[LvObj], dir: c_int) -> None: ...
def lv_dropdown_set_symbol(obj: c_ptr[LvObj], symbol: str | None) -> None: ...
def lv_dropdown_set_selected_highlight(obj: c_ptr[LvObj], en: c_bool) -> None: ...
def lv_dropdown_get_selected(obj: c_ptr[LvObj]) -> c_uint: ...
def lv_dropdown_get_option_count(obj: c_ptr[LvObj]) -> c_uint: ...
def lv_dropdown_get_list(obj: c_ptr[LvObj]) -> c_ptr[LvObj]: ...
def lv_dropdown_open(obj: c_ptr[LvObj]) -> None: ...
def lv_dropdown_close(obj: c_ptr[LvObj]) -> None: ...
def lv_dropdown_is_open(obj: c_ptr[LvObj]) -> c_bool: ...


# ============================================================================
# Disabled widgets (LV_USE_*=0 in lv_conf.h)
# ============================================================================
#
# The following widgets are disabled to reduce firmware size:
# - Textarea (LV_USE_TEXTAREA=0)
# - Roller (LV_USE_ROLLER=0)
# - Spinbox (LV_USE_SPINBOX=0)
# - Image (LV_USE_IMAGE=0)
# - Line (LV_USE_LINE=0)
# - Canvas (LV_USE_CANVAS=0)
# - Tabview (LV_USE_TABVIEW=0)
# - Buttonmatrix (LV_USE_BUTTONMATRIX=0)
# - Keyboard (LV_USE_KEYBOARD=0)
# - Span (LV_USE_SPAN=0)
# - Msgbox (LV_USE_MSGBOX=0)
# - Scale (LV_USE_SCALE=0)
# - Chart (LV_USE_CHART=0)
# - LED (LV_USE_LED=0)
# - List (LV_USE_LIST=0)
# - Menu (LV_USE_MENU=0)
#
# To enable a widget:
# 1. Set LV_USE_<WIDGET>=1 in modules/usermod_lvgl/lv_conf.h
# 2. Add the widget stubs here
# 3. Run: make compile-lvgl
# ============================================================================
